In [14]:
import pandas as pd
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
import pycountry_convert as pc
import numpy as np


%store -r Spo_Data

Spo_Data.head()

acousticness                                   artists  danceability  \
0         0.995                       ['Carl Woitschach']         0.708   
1         0.994  ['Robert Schumann', 'Vladimir Horowitz']         0.379   
2         0.604                   ['Seweryn Goszczyński']         0.749   
3         0.995                      ['Francisco Canaro']         0.781   
4         0.990  ['Frédéric Chopin', 'Vladimir Horowitz']         0.210   

   duration_ms  energy  explicit                      id  instrumentalness  \
0       158648  0.1950         0  6KbQ3uYMLKb5jDxLF7wYDD             0.563   
1       282133  0.0135         0  6KuQTIu1KoTTkLXKrwlLPV             0.901   
2       104300  0.2200         0  6L63VW0PibdM1HDSBoqnoM             0.000   
3       180760  0.1300         0  6M94FkXd15sOAOQYRnWPN8             0.887   
4       687733  0.2040         0  6N6tiFZ9vLTSOIxkj8qKrd             0.908   

   key  liveness  loudness  mode  \
0   10    0.1510   -12.428     1   
1    8    0.0763   -28.454     1   
2    5    0.1190   -19.924     0   
3    1    0.1110   -14.734     0   
4   11    0.0980   -16.829     1   

                                            name  popularity release_date  \
0                    Singende Bataillone 1. Teil           0         1928   
1       Fantasiestücke, Op. 111: Più tosto lento           0         1928   
2                 Chapter 1.18 - Zamek kaniowski           0         1928   
3  Bebamos Juntos - Instrumental (Remasterizado)           0   1928-09-25   
4    Polonaise-Fantaisie in A-Flat Major, Op. 61           1         1928   

   speechiness    tempo  valence  year  
0       0.0506  118.469   0.7790  1928  
1       0.0462   83.972   0.0767  1928  
2       0.9290  107.177   0.8800  1928  
3       0.0926  108.003   0.7200  1928  
4       0.0424   62.149   0.0693  1928

In [4]:
Spo_Data.isnull().sum()

acousticness        0
artists             0
danceability        0
duration_ms         0
energy              0
explicit            0
id                  0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
name                0
popularity          0
release_date        0
speechiness         0
tempo               0
valence             0
year                0
dtype: int64

In [23]:
Spo_Clean_Data=Spo_Data.drop(['id','name'], axis=1)
Spo_Clean_Data

acousticness  artists  danceability  duration_ms  energy  explicit  \
0             0.9950     4880         0.708       158648  0.1950         0   
1             0.9940    25163         0.379       282133  0.0135         0   
2             0.6040    26351         0.749       104300  0.2200         0   
3             0.9950     9738         0.781       180760  0.1300         0   
4             0.9900    10245         0.210       687733  0.2040         0   
...              ...      ...           ...          ...     ...       ...   
169904        0.1730     8004         0.875       163800  0.4430         1   
169905        0.0167    17559         0.719       167468  0.3850         0   
169906        0.5380    16987         0.514       180700  0.5390         0   
169907        0.0714     5031         0.646       167308  0.7610         0   
169908        0.1090    13224         0.512       214787  0.4280         0   

        instrumentalness  key  liveness  loudness  mode  popularity  \
0               0.563000   10    0.1510   -12.428     1           0   
1               0.901000    8    0.0763   -28.454     1           0   
2               0.000000    5    0.1190   -19.924     0           0   
3               0.887000    1    0.1110   -14.734     0           0   
4               0.908000   11    0.0980   -16.829     1           1   
...                  ...  ...       ...       ...   ...         ...   
169904          0.000032    1    0.0891    -7.461     1          75   
169905          0.031300    8    0.1110   -10.907     1          64   
169906          0.002330    7    0.1080    -9.332     1          70   
169907          0.000000    1    0.2220    -2.557     1          70   
169908          0.000000    0    0.1050    -7.387     1          65   

       release_date  speechiness    tempo  valence  year  
0              1928       0.0506  118.469   0.7790  1928  
1              1928       0.0462   83.972   0.0767  1928  
2              1928       0.9290  107.177   0.8800  1928  
3        1928-09-25       0.0926  108.003   0.7200  1928  
4              1928       0.0424   62.149   0.0693  1928  
...             ...          ...      ...      ...   ...  
169904   2020-05-15       0.1430  100.012   0.3060  2020  
169905   2020-06-08       0.0403  128.000   0.2700  2020  
169906   2020-05-29       0.1050  123.700   0.1530  2020  
169907   2020-02-28       0.0385  129.916   0.4720  2020  
169908   2020-03-27       0.0271   80.588   0.3660  2020  

[169909 rows x 17 columns]

In [24]:
labelencoder = LabelEncoder()
Spo_Clean_Data['artists'] = labelencoder.fit_transform(Spo_Data['artists'])
Spo_Clean_Data


acousticness  artists  danceability  duration_ms  energy  explicit  \
0             0.9950     4880         0.708       158648  0.1950         0   
1             0.9940    25163         0.379       282133  0.0135         0   
2             0.6040    26351         0.749       104300  0.2200         0   
3             0.9950     9738         0.781       180760  0.1300         0   
4             0.9900    10245         0.210       687733  0.2040         0   
...              ...      ...           ...          ...     ...       ...   
169904        0.1730     8004         0.875       163800  0.4430         1   
169905        0.0167    17559         0.719       167468  0.3850         0   
169906        0.5380    16987         0.514       180700  0.5390         0   
169907        0.0714     5031         0.646       167308  0.7610         0   
169908        0.1090    13224         0.512       214787  0.4280         0   

        instrumentalness  key  liveness  loudness  mode  popularity  \
0               0.563000   10    0.1510   -12.428     1           0   
1               0.901000    8    0.0763   -28.454     1           0   
2               0.000000    5    0.1190   -19.924     0           0   
3               0.887000    1    0.1110   -14.734     0           0   
4               0.908000   11    0.0980   -16.829     1           1   
...                  ...  ...       ...       ...   ...         ...   
169904          0.000032    1    0.0891    -7.461     1          75   
169905          0.031300    8    0.1110   -10.907     1          64   
169906          0.002330    7    0.1080    -9.332     1          70   
169907          0.000000    1    0.2220    -2.557     1          70   
169908          0.000000    0    0.1050    -7.387     1          65   

       release_date  speechiness    tempo  valence  year  
0              1928       0.0506  118.469   0.7790  1928  
1              1928       0.0462   83.972   0.0767  1928  
2              1928       0.9290  107.177   0.8800  1928  
3        1928-09-25       0.0926  108.003   0.7200  1928  
4              1928       0.0424   62.149   0.0693  1928  
...             ...          ...      ...      ...   ...  
169904   2020-05-15       0.1430  100.012   0.3060  2020  
169905   2020-06-08       0.0403  128.000   0.2700  2020  
169906   2020-05-29       0.1050  123.700   0.1530  2020  
169907   2020-02-28       0.0385  129.916   0.4720  2020  
169908   2020-03-27       0.0271   80.588   0.3660  2020  

[169909 rows x 17 columns]

In [25]:
Spo_Clean_Data

acousticness  artists  danceability  duration_ms  energy  explicit  \
0             0.9950     4880         0.708       158648  0.1950         0   
1             0.9940    25163         0.379       282133  0.0135         0   
2             0.6040    26351         0.749       104300  0.2200         0   
3             0.9950     9738         0.781       180760  0.1300         0   
4             0.9900    10245         0.210       687733  0.2040         0   
...              ...      ...           ...          ...     ...       ...   
169904        0.1730     8004         0.875       163800  0.4430         1   
169905        0.0167    17559         0.719       167468  0.3850         0   
169906        0.5380    16987         0.514       180700  0.5390         0   
169907        0.0714     5031         0.646       167308  0.7610         0   
169908        0.1090    13224         0.512       214787  0.4280         0   

        instrumentalness  key  liveness  loudness  mode  popularity  \
0               0.563000   10    0.1510   -12.428     1           0   
1               0.901000    8    0.0763   -28.454     1           0   
2               0.000000    5    0.1190   -19.924     0           0   
3               0.887000    1    0.1110   -14.734     0           0   
4               0.908000   11    0.0980   -16.829     1           1   
...                  ...  ...       ...       ...   ...         ...   
169904          0.000032    1    0.0891    -7.461     1          75   
169905          0.031300    8    0.1110   -10.907     1          64   
169906          0.002330    7    0.1080    -9.332     1          70   
169907          0.000000    1    0.2220    -2.557     1          70   
169908          0.000000    0    0.1050    -7.387     1          65   

       release_date  speechiness    tempo  valence  year  
0              1928       0.0506  118.469   0.7790  1928  
1              1928       0.0462   83.972   0.0767  1928  
2              1928       0.9290  107.177   0.8800  1928  
3        1928-09-25       0.0926  108.003   0.7200  1928  
4              1928       0.0424   62.149   0.0693  1928  
...             ...          ...      ...      ...   ...  
169904   2020-05-15       0.1430  100.012   0.3060  2020  
169905   2020-06-08       0.0403  128.000   0.2700  2020  
169906   2020-05-29       0.1050  123.700   0.1530  2020  
169907   2020-02-28       0.0385  129.916   0.4720  2020  
169908   2020-03-27       0.0271   80.588   0.3660  2020  

[169909 rows x 17 columns]

In [26]:

%store Spo_Clean_Data

Stored 'Spo_Clean_Data' (DataFrame)


In [56]:

T_array = np.array(Spo_Clean_Data['tempo'])
normalized_T = preprocessing.normalize([T_array])
normalized_T

array([[0.00237689, 0.00168476, 0.00215033, ..., 0.00248184, 0.00260655,
        0.00161687]])

In [57]:
L_array = np.array(Spo_Clean_Data['loudness'])
normalized_L = preprocessing.normalize([L_array])
normalized_L

array([[-0.00237327, -0.00543362, -0.00380472, ..., -0.00178205,
        -0.00048829, -0.00141063]])

In [58]:
D_array = np.array(Spo_Clean_Data['duration_ms'])
normalized_D = preprocessing.normalize([D_array])
normalized_D

array([[0.00147305, 0.00261962, 0.00096843, ..., 0.00167781, 0.00155346,
        0.00199431]])

In [69]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# 4 samples/observations and 2 variables/features
X = np.Spo_Clean_Data['tempo']
# the scaler object (model)
scaler = StandardScaler()
# fit and transform the data
scaled_data = scaler.fit_transform(X) 

AttributeError: module 'numpy' has no attribute 'Spo_Clean_Data'