In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl



%store -r Spo_Clean_Data

%store -r Spo_Data

Spo_Clean_Data.head()

acousticness  artists  danceability  duration_ms  energy  explicit  \
0         0.995     4880         0.708     0.028442  0.1950         0   
1         0.994    25163         0.379     0.051316  0.0135         0   
2         0.604    26351         0.749     0.018374  0.2200         0   
3         0.995     9738         0.781     0.032538  0.1300         0   
4         0.990    10245         0.210     0.126450  0.2040         0   

   instrumentalness  key  liveness  loudness  mode  popularity  speechiness  \
0             0.563   10    0.1510  0.745000     1        0.00       0.0506   
1             0.901    8    0.0763  0.494026     1        0.00       0.0462   
2             0.000    5    0.1190  0.627609     0        0.00       0.9290   
3             0.887    1    0.1110  0.708887     0        0.00       0.0926   
4             0.908   11    0.0980  0.676079     1        0.01       0.0424   

      tempo  valence  year  day  month  
0  0.485348   0.7790  1928    1      1  
1  0.344019   0.0767  1928    1      1  
2  0.439086   0.8800  1928    1      1  
3  0.442470   0.7200  1928   25      9  
4  0.254614   0.0693  1928    1      1

In [2]:
dataset = Spo_Clean_Data
X = dataset.drop('year', axis=1)
y = dataset['year']


In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [4]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [6]:
y_pred = classifier.predict(X_test)
y_pred

array([1952, 2015, 1986, ..., 1940, 1998, 2002], dtype=int64)

In [7]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 13   0   0 ...   0   0   0]
 [  0   3   3 ...   0   0   0]
 [  0   2  11 ...   0   0   0]
 ...
 [  0   0   0 ...  92  57  29]
 [  0   0   0 ...  52 121  33]
 [  0   0   0 ...  32  41 144]]
              precision    recall  f1-score   support

        1921       0.42      0.46      0.44        28
        1922       0.33      0.20      0.25        15
        1923       0.24      0.29      0.27        38
        1924       0.33      0.27      0.30        45
        1925       0.42      0.44      0.43        55
        1926       0.66      0.64      0.65       182
        1927       0.56      0.63      0.59       111
        1928       0.66      0.72      0.69       232
        1929       0.76      0.79      0.78       169
        1930       0.39      0.36      0.38       387
        1931       0.73      0.80      0.76       115
        1932       0.32      0.36      0.34        87
        1933       0.53      0.48      0.50       133
        1934       0.55      0.56      0.56       1

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [9]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(X_train, y_train)

DecisionTreeRegressor()

In [11]:
y_pred = regressor.predict(X_test)

In [12]:
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
df

Actual  Predicted
34530     1963     1952.0
54303     2007     1970.0
119544    1954     1957.0
132124    1986     1989.0
165993    1981     1975.0
...        ...        ...
27979     1978     1982.0
108428    1937     1953.0
83427     1974     1975.0
67859     1992     1991.0
110456    1958     1973.0

[33982 rows x 2 columns]

In [13]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 8.645272987660134
Mean Squared Error: 162.51334366560073
Root Mean Squared Error: 12.748072154863289
