In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl



%store -r Spo_Clean_Data

%store -r Spo_Data

Spo_Clean_Data.head()

acousticness  artists  danceability  duration_ms  energy  explicit  \
0         0.995     4880         0.708     0.028442  0.1950         0   
1         0.994    25163         0.379     0.051316  0.0135         0   
2         0.604    26351         0.749     0.018374  0.2200         0   
3         0.995     9738         0.781     0.032538  0.1300         0   
4         0.990    10245         0.210     0.126450  0.2040         0   

   instrumentalness  key  liveness  loudness  mode  popularity  speechiness  \
0             0.563   10    0.1510  0.745000     1        0.00       0.0506   
1             0.901    8    0.0763  0.494026     1        0.00       0.0462   
2             0.000    5    0.1190  0.627609     0        0.00       0.9290   
3             0.887    1    0.1110  0.708887     0        0.00       0.0926   
4             0.908   11    0.0980  0.676079     1        0.01       0.0424   

      tempo  valence  year  Month  Day  
0  0.485348   0.7790  1928      1    1  
1  0.344019   0.0767  1928      1    1  
2  0.439086   0.8800  1928      1    1  
3  0.442470   0.7200  1928      9   25  
4  0.254614   0.0693  1928      1    1

In [6]:
dataset = Spo_Clean_Data
X = dataset.drop('year', axis=1)
y = dataset['year']


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [8]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [10]:
y_pred = classifier.predict(X_test)
y_pred

array([1946, 1988, 1984, ..., 1936, 1947, 2007], dtype=int64)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 12   1   1 ...   0   0   0]
 [  0   9   1 ...   0   0   0]
 [  0   4   9 ...   0   0   0]
 ...
 [  0   0   0 ...  73  68  33]
 [  0   0   0 ...  69 117  30]
 [  0   0   0 ...  35  45 189]]
              precision    recall  f1-score   support

        1921       0.55      0.40      0.46        30
        1922       0.47      0.56      0.51        16
        1923       0.21      0.28      0.24        32
        1924       0.40      0.39      0.39        49
        1925       0.29      0.36      0.32        39
        1926       0.66      0.67      0.67       166
        1927       0.58      0.62      0.60       132
        1928       0.72      0.68      0.70       244
        1929       0.76      0.79      0.77       173
        1930       0.37      0.39      0.38       348
        1931       0.78      0.78      0.78       129
        1932       0.48      0.52      0.50       111
        1933       0.49      0.49      0.49       114
        1934       0.52      0.49      0.50       1

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [13]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(X_train, y_train)

DecisionTreeRegressor()

In [14]:
y_pred = regressor.predict(X_test)

In [15]:
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
df

Actual  Predicted
34530     1963     1952.0
54303     2007     1970.0
119544    1954     1956.0
132124    1986     1982.0
165993    1981     1969.0
...        ...        ...
27979     1978     1980.0
108428    1937     1948.0
83427     1974     1990.0
67859     1992     1991.0
110456    1958     1973.0

[33982 rows x 2 columns]

In [16]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 8.684906715319876
Mean Squared Error: 163.05657325119833
Root Mean Squared Error: 12.76936072210345
